version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: ~/tabsleeper
    docker:
      - image: cimg/node:20.8.1
    steps:
      - checkout
      - run: ./script/setup
      - run: ./script/build
      - run: ./script/package
      - store_artifacts:
          path: 'output/packages'
          destination: 'packages'
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build-release-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
